# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Brent Danley
tagline:          A Jekyll GitHub Page
url:              http://brentdanley.com/
paginate:         1
baseurl:          /
author:
  name:           Brent Danley
  url:            https://twitter.com/brentdanley
  email:          brentdanley@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/brentdanley/brentdanley.github.io

# Exclude
exclude:
  - sass