# Permalinks
permalink:        pretty

# Setup
title:            Brent Danley's GitHub Projects
tagline:          Brent Danley's GitHub Pages site, coded in Jekyll
url:              https://brentdanley.github.io
paginate:         
baseurl:          /
author:
  name:           Brent Danley
  url:            https://twitter.com/brentdanley
  email:          brentdanley@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/brentdanley/brentdanley.github.io

# Exclude
exclude: [Gemfile, Gemfile.lock, config.rb, README.md]

# Defaults
defaults: 
  scope:
    path: "assets/img"
  values:
    image: true

sass: 
  sass_dir: _sass